apiVersion: v2
name: argocd
description: A Helm chart for deploying ArgoCD
type: application
version: 0.1.1
appVersion: "2.11.7"
dependencies:
  - name: argo-cd
    version: "7.3.11"
    repository: "https://argoproj.github.io/argo-helm"